Registreringsapplikation/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users, :only => [:create, :new, :index, :show, :destroy]
  resources :api_keys, :only => [:create, :new, :index, :destroy]

  get   'allusers'   => 'users#show', as: :allusers
  post  'login'   => 'users#login', as: :login
  get   'logout'  => 'users#logout', as: :logout

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "/test" => 'sessions#test'
  get "/authenticate" => "sessions#authenticate"
  get "/unauthorized" => "sessions#unauthorized", :as => :unauthorized
  get "/unauthorized_key" => "sessions#unauthorized_key", :as => :unauthorized_key

  get '/api/v1/games/tag/:id' => 'api/v1/games#tag', :as => :games_tag
  
  get '/api/v1/games/search_for/:team_id' => 'api/v1/games#search_for', :as => :games_search_for
  
  post '/api/v1/games/:id/tag/:tag_id' => 'api/v1/games#add_tag', :as => :games_add_tag
  delete '/api/v1/games/:id/tag/:tag_id' => 'api/v1/games#remove_tag', :as => :games_remove_tag
  
  match '*any' => 'application#options', :via => [:options]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :games
      resources :locations
      resources :tags
      resources :teams

      root to: 'games#index'

    end
  end

end

Registreringsapplikation/app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  belongs_to :user
  before_create :generate_key
  validates :app_name,
            :length => {:minimum => 2, :message => ", you need at least 2 letters in your app name"}

  private
  def generate_key
    begin self.key = SecureRandom.hex(24)
    end while self.class.exists?(key: key)
  end
end

Registreringsapplikation/app/controllers/api_keys_controller.rb
class ApiKeysController < ApplicationController
  before_action :require_login
  def index
    @keys = ApiKey.find_by_user_id(current_user.id)
  end

  def new
    @key = ApiKey.new
  end

  def create
    @key = ApiKey.new(key_params)
    @key.user = current_user

    if @key.save
      redirect_to api_keys_path
    else
      render :action => "new"
    end
  end

  def destroy
    @key = ApiKey.find(destroy_params[:id])

    if @key.user == current_user or current_user.is_admin?

      if @key.destroy
        flash[:notice] = "Api Key was deleted"
        redirect_to api_keys_path
      else
        flash[:notice] = "Api Key was not deleted"
      end
    else
      flash[:notice] = "Failed"
    end
  end

  private

  def key_params
    params.require(:api_key).permit(:app_name)
  end
  def destroy_params
    params.permit(:id)
  end
end

Registreringsapplikation/app/helpers/api_keys_helper.rb
module ApiKeysHelper
end

Registreringsapplikation/app/helpers/apikeys_helper.rb
module ApikeysHelper
end

Registreringsapplikation/app/views/api_keys/index.html.erb
<h1>Api keys</h1>
<% if flash[:notice] %>
    <div>
      <%= flash[:notice] %>
    </div>
<% end %>

<div>
  <h3>Logged in as <%= current_user.email %></h3>
  <ul>
    <% current_user.api_keys.each do |key| %>
      <li>
        <%= key.app_name %>
        <ul>
          <li><%= key.key %></li>
          <li><%= button_to "Delete key", key, :method => "delete" %></li>
        </ul>
      </li>

    <% end %>
  </ul>
</div>

<% if current_user.is_admin?%>
    <%= link_to "Back to users", allusers_path %>
<% else %>
    <%= link_to "New key", new_api_key_path %>
<% end %>
<%= link_to "Delete user account", current_user, :method => "delete" %>
<%= link_to "Logout", logout_path %>

Registreringsapplikation/app/views/api_keys/new.html.erb
<% if @key.errors.any? %>
    <div>
      <ul>
        <% @key.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div>
  <%= form_for @key do |f| %>
    <%= f.label :app_name %>
      <%= f.text_field :app_name %>
      <%= f.submit "Register" %>
  <% end %>
  <%= link_to "Back", api_keys_path %>
</div>

Registreringsapplikation/app/views/api_keys/show.html.erb
<h1>Api keys</h1>
<% if flash[:notice] %>
    <div>
      <%= flash[:notice] %>
    </div>
<% end %>

<div>
  <h3>Logged in as <%= current_user.email %></h3>
  <ul>
    <% current_user.api_keys.each do |key| %>
      <li>
        <%= key.app_name %>
        <ul>
          <li><%= key.key %></li>
          <li><%= button_to "Delete key", key, :method => "delete" %></li>
        </ul>
      </li>

    <% end %>
  </ul>
</div>

<% if current_user.is_admin?%>
    <%= link_to "Back to users", allusers_path %>
<% else %>
    <%= link_to "New key", new_api_key_path %>
<% end %>
<%= link_to "Logout", logout_path %>