Registreringsapplikation/config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users, :only => [:create, :new, :index, :show, :destroy]
  resources :api_keys, :only => [:create, :new, :index, :destroy]

  get   'allusers'   => 'users#show', as: :allusers
  post  'login'   => 'users#login', as: :login
  get   'logout'  => 'users#logout', as: :logout

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  get "/test" => 'sessions#test'
  get "/authenticate" => "sessions#authenticate"
  get "/unauthorized" => "sessions#unauthorized", :as => :unauthorized
  get "/unauthorized_key" => "sessions#unauthorized_key", :as => :unauthorized_key

  get '/api/v1/games/tag/:id' => 'api/v1/games#tag', :as => :games_tag
  
  get '/api/v1/games/search_for/:team_id' => 'api/v1/games#search_for', :as => :games_search_for
  
  post '/api/v1/games/:id/tag/:tag_id' => 'api/v1/games#add_tag', :as => :games_add_tag
  delete '/api/v1/games/:id/tag/:tag_id' => 'api/v1/games#remove_tag', :as => :games_remove_tag
  
  match '*any' => 'application#options', :via => [:options]

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :games
      resources :locations
      resources :tags
      resources :teams

      root to: 'games#index'

    end
  end

end

Registreringsapplikation/app/models/user.rb
class User < ActiveRecord::Base
  has_many :api_keys
  has_secure_password

  validates :email,
            :uniqueness => true,
            :length => {:minimum => 4, :message => ", you need at least 4 letters in your e-mail"}
  validates_format_of :email,
                      :with => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :password,
            :length => {:minimum => 6, :message => ", your password needs to contain at least 6 letters"}

  def is_admin?
    self.role.downcase == "administrator"
  end
end

Registreringsapplikation/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end
  def show
    unless current_user.is_admin?
      redirect_to api_keys_path
    end
    @users = User.all
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)

    if @user.save
      session[:userid] = @user.id
      redirect_to api_keys_path
    else
      render :action => "new"
    end
  end

  def login
    u = User.find_by_email(params[:email])
    if u && u.authenticate(params[:password])
      session[:userid] = u.id

      if u.is_admin?
        redirect_to allusers_path
      else
        redirect_to api_keys_path
      end
    else
      flash[:notice] = "Failed to login"
      redirect_to root_path
    end
  end

  def logout
    session[:userid] = nil
    redirect_to root_path, :notice => "Logged out"
  end

  def destroy
    @user = User.find(destroy_params[:id])

    if @user == current_user or current_user.is_admin?

      if @user.destroy
        flash[:notice] = "User was deleted"
        if current_user.is_admin?
          redirect_to allusers_path
        else
          redirect_to root_path
        end
      else
        flash[:notice] = "User was not deleted"
      end
    else
      flash[:notice] = "Failed"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
  def destroy_params
    params.permit(:id)
  end
end

Registreringsapplikation/app/helpers/users_helper.rb
module UsersHelper
end

Registreringsapplikation/app/views/users/index.html.erb
<% if flash[:notice] %>
  <div>
    <%= flash[:notice] %>
  </div>
<% end %>

<div>
  <fieldset>
    <%= form_tag(login_path, method: "post") do %>
        <p><%= label_tag(:email, "E-mail") %></p>
        <p><%= email_field_tag(:email) %></p>

        <p><%= label_tag(:password, "Password") %></p>
        <p><%= password_field_tag(:password) %></p>
        <p><%= submit_tag("Log in") %></p>

    <% end %>
  </fieldset>

  <%= link_to "Register", new_user_path %>
</div>

Registreringsapplikation/app/views/users/new.html.erb
<h1>Create new user</h1>

<% if @user.errors.any? %>
    <div>
      <h2><%= pluralize(@user.errors.count, "Error") %> in the form made it impossible to save:</h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for @user do |f| %>
    <div>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    <div>
      <%= f.submit "Register" %>
    </div>
<% end %>

<%= link_to "Back to login", root_path %>

Registreringsapplikation/app/views/users/show.html.erb
<h1>All users and keys</h1>
<div>
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= user.email %>
        <%= button_to "Delete user account", user, :method => "delete" %>
        <ul>
          <% user.api_keys.each do |key| %>
              <li>
                <%= key.app_name %>
                <ul>
                  <li>
                    <%= key.key %>
                    <%= button_to "Delete key", key, :method => "delete" %>
                  </li>
                </ul>
              </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to "New key", new_api_key_path %>
<%= link_to "Logout", logout_path %>